# Generated by Django 4.1.1 on 2022-09-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="companyName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=200, unique=True),
                ),
            ],
            options={"verbose_name_plural": "Name of Companies",},
        ),
        migrations.CreateModel(
            name="PostLocationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, max_length=200, null=True, unique=True
                    ),
                ),
            ],
            options={"verbose_name_plural": "LocationCategories",},
        ),
        migrations.CreateModel(
            name="TrainingCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, max_length=200, null=True, unique=True
                    ),
                ),
            ],
            options={"verbose_name_plural": "TrainingCategories",},
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trainingImage",
                    models.ImageField(
                        blank=True, upload_to="cooperation/images/training/%Y/%m/%d/"
                    ),
                ),
                ("trainingTitle", models.CharField(max_length=50)),
                ("trainingType", models.CharField(max_length=30)),
                ("trainingContents", models.TextField()),
                (
                    "trainingFile",
                    models.FileField(
                        blank=True, upload_to="cooperation/files/training/%Y/%m/%d/"
                    ),
                ),
                (
                    "trainingCategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cooperation.trainingcategory",
                    ),
                ),
                (
                    "trainingcompanyName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_CompanyName",
                        to="cooperation.companyname",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "companyImage",
                    models.ImageField(
                        blank=True, upload_to="cooperation/images/%Y/%m/%d/"
                    ),
                ),
                ("companyHook", models.CharField(blank=True, max_length=100)),
                ("companyNumber", models.CharField(blank=True, max_length=13)),
                ("companyInform", models.CharField(max_length=500)),
                ("companyDomain", models.URLField()),
                (
                    "companyLocationCategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cooperation.postlocationcategory",
                    ),
                ),
                (
                    "companyName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_CompanyName",
                        to="cooperation.companyname",
                    ),
                ),
            ],
        ),
    ]
