# Generated by Django 4.1.1 on 2022-09-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooperation", "0002_rename_trainingcompanyname_training_companyname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyname",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="companyInform",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="postlocationcategory",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
