# Generated by Django 3.0.5 on 2022-09-25 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0004_alter_post_companyinform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyname',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='companyName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_CompanyName', to='cooperation.CompanyName'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='postlocationcategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='training',
            name='companyName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_CompanyName', to='cooperation.CompanyName'),
        ),
        migrations.AlterField(
            model_name='training',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trainingcategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
