# Generated by Django 4.1.1 on 2022-09-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zblog', '0002_post_updated_at_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='head_img',
            field=models.ImageField(blank=True, upload_to='blog/images/%Y/%m/%d/'),
        ),
    ]
