# Generated by Django 4.1.1 on 2022-09-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='user_disability',
            field=models.CharField(max_length=100, verbose_name='장애'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user_gender',
            field=models.CharField(max_length=100, verbose_name='성별'),
        ),
    ]
