# Generated by Django 3.0.5 on 2022-09-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30, unique=True, verbose_name='아이디')),
                ('user_pw', models.CharField(max_length=50, verbose_name='비밀번호')),
                ('user_name', models.CharField(max_length=30, unique=True, verbose_name='이름')),
                ('user_gender', models.CharField(max_length=10, verbose_name='성별')),
                ('user_disable', models.CharField(max_length=10, verbose_name='장애')),
                ('user_phonenum', models.CharField(max_length=20, verbose_name='전화번호')),
                ('user_interest', models.CharField(max_length=30, verbose_name='관심분야')),
            ],
        ),
    ]
