# Generated by Django 3.0.5 on 2022-09-23 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_disable',
            new_name='user_disability',
        ),
    ]
